name: Reqres
on: 
  push:
    paths:
    - 'cypress/e2e/3-apitesting/reqres.cy.js'
jobs:
  cypress-run:
    name: Reqres
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regression Reqres
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/4-webtesting/orangeHRM.cy.js
            cypress/e2e/3-apitesting/reqres.cy.js